# Generated by Django 4.1.3 on 2022-11-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_songs_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='image',
            field=models.ImageField(upload_to='media/image'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='song',
            field=models.FileField(upload_to='media/songs'),
        ),
    ]
