# Generated by Django 4.1.3 on 2022-11-11 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_songs_image_alter_songs_song'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Songs',
            new_name='Song',
        ),
    ]
